ENTITY_LEXICON = {
    "INGREDIENTE": [
        "camarao",
        "carne de sol",
        "peixe",
        "polvo",
        "lula",
        "frango",
        "file",
        "presunto",
        "queijo",
        "queijo coalho",
        "mussarela",
        "catupiry",
        "parmesao",
        "alho",
        "manteiga",
        "nata",
        "tomate",
        "cebola",
        "cogumelos",
        "castanha",
        "ervilha",
        "brocolis",
    ],
    "ACOMPANHAMENTO": [
        "arroz",
        "arroz cremoso",
        "arroz de brocolis",
        "risoto",
        "fettuccine",
        "nhoque",
        "batata palha",
        "batata",
        "macaxeira",
        "macaxeira frita",
        "pure de macaxeira",
        "pure",
        "farofa",
        "legumes",
        "torradas",
    ],
    "MOLHO_TECNICA": [
        "molho branco",
        "molho de tomate",
        "molho madeira",
        "milanesa",
        "gratinado",
        "manteiga do sertao",
        "salteado",
        "empanado",
        "grelhado",
        "refogado",
        "ao forno",
    ],
}


ACTIVE_ENTITY_LEXICON = {category: list(terms) for category, terms in ENTITY_LEXICON.items()}
